@extends('layouts/index')
@section('title', 'TERM')
@section('contents')
<!--  top bar -->
<!--  end top bar -->
<!--  navigation -->
 @include('partial.header')
<!--  end navigation -->
<!--  page banner -->
  <div id="page-banner" class="page-banner-main" style="background-image: url('{{ asset('assets/images/homebanner.jpg') }}')">
  <div class="overlay-bg"></div>    
    <div class="page-banner-text text-center">
      <h3 class="page-baner-hedding">Term</h3>  
      <ol class="breadcrumb">
        <li><a href="{{ route('index') }}">Home</a></li>
        <li class="active">Term</li>
      </ol>     
    </div> 
  </div>
<!--  end page banner -->
<!--  overview -->
  <div id="career-page" class="career-page-main-block">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h3 class="overview-heading">TERMS OF USE</h3> <br>           
          <hr>
          <div class="overview-post">
            <p><em>1. GENERAL</em>This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
            <p><em>1.</em>  This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of  Ghar ka Patta</p>
            <p><em>1.</em>The domain name www.squareyards.com ("Website"), is owned and operated by Square Yards Consulting Pvt. Ltd. ("Company") a Private Company limited by shares, incorporated under the provisions of the Companies Act, 2013, and having its registered office at Corporate Office 9th Floor, Good Earth Business Bay, Sector 58, Gurgaon -122011, where such expression shall, unless repugnant to the context thereof, be deemed to include its respective representatives, administrators, employees, directors, officers, agents and their successors and assigns.</p>
            <p><em>1.</em> This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
            <p><em>1.</em> This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
            <p><em>1.</em> This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>

          </div> 
          <h5 class="overview-heading">TERM</h5>
          <hr>
          <div class="overview-post">
            <p><em>1.</em>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors.</p>
            <p><em>1.</em>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors.</p>
            <p><em>1.</em>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors.</p><p><em>1.</em>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors.</p>
            
            <p>Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like</p>
          </div> 
        </div>
      </div>
    </div>
  </div>
<!--  end overview -->


<!-- footer -->
@include('partial.footer')
<!--  end footer -->
@endsection
